### ISSUE TITLE
`spago build` appears to include the test directory of (local) dependencies

### ISSUE THREAD

**Issue by LiamGoodacre** [spacchetti/spago#102]
I'm getting a compilation error saying that `Main` has been defined multiple times and it's pointing at the test directory of my local dependencies.

**Comment by f-f** [comment]
No problem! 🙂

**Comment by LiamGoodacre** [comment]
I had some existing local dependencies that I was converting to try out spago.
I ran `spago init` in the respective project directories to get spago.dhall and packages.dhall - but I didn't realise it also created a `src/Main.purs` file.

**Comment by btrepp** [comment]
I have done this a few times too. It's no biggy, but maybe init with files shouldn't create a main.purs?.

**Comment by JordanMartinez** [comment]
Or, perhaps it should by default but there should be a flag to prevent
that.

**Comment by JordanMartinez** [comment]
Let's step back and consider the different reasons why this would be useful and annoying.

If one is migrating from psc-package to spago, then it's probable that the user already has their project structure set up correctly. They simply want to migrate to spago. Thus, adding a Main.purs file would be annoying to them.

If one is starting a new project via spago, then it would be nice if spago created all the necessary project structure: `src` and `test` folders and other spago-related files. Thus, adding a Main.purs file would be convenient and appreciated by them.

Others might want to use spago to write a library (as that can be done now via `0.6.4.0`, right?) but I don't think that's a common activity yet.

So, there are a few options here:
- address all concerns in one command, `init`, with reasonable defaults and provide flags to customize it as needed for special situations
- address the migration concern in a separate command (i.e. `psc-package-migrate`?) from the new project/library concern via the command, `init`

**Comment by f-f** [comment]
@JordanMartinez good points 👍 

A small note first: the detection "can we migrate a psc-package file" doesn't happen specifically in the `init`, but every time Spago needs a `spago.dhall`, so this is not as clean-cut as I'd like it to be (the whole "is our configuration here" probably needs some refactoring)

Also I would like to keep the CLI-surface as small as possible, and I wouldn't like to add another command that does almost the same thing as `init`.

So there's a "fix" up in #105, I went with checking if `src` and `test` exist, and skipping the file copy if they do, so e.g. it would prevent what happened to @LiamGoodacre and @btrepp.
If one has sources in another folders it would still not be a problem, because they are not included by default in Spago (and here I wonder if the `Config` should have a setting for specifying the "source paths", since it's a common use-case)

**Comment by JordanMartinez** [comment]
Thanks for the clarification! 
Yeah, keeping the CLI-surface small makes sense. I'd prefer that anyway.
