### ISSUE TITLE
spago's own package set

### ISSUE THREAD

**Issue by voland62** [spacchetti/spago#118]
It seems like spago uses it's own package set, kind of: 
https://raw.githubusercontent.com/spacchetti/spacchetti/0.12.2-20190221/src/packages.dhall
, but this one https://github.com/purescript/package-sets - seems like unused now, right?

Just for clarification...

**Comment by f-f** [comment]
Hi @voland62! The brief context is that [spacchetti](https://github.com/spacchetti/spacchetti) was born so that we could experiment with Dhall-powered package-sets. 

At this point in time `spacchetti` and the "official" package-set basically contain the same packages so that's why `spago` uses `spacchetti`, while `psc-package` uses `package-sets`.
The two are both actively maintained by @justinwoo, who keeps them in sync; so you can consider them both active projects. However, only `spacchetti` can be used by `spago`.

I've been considering proposing the unification of the two into `package-sets` so that both `spago` and `psc-package` would be on the same package-set.

**Comment by voland62** [comment]
Thanks for clarification.

  I actually was surprised a bit, when I clouldn't find "sodium" package in spacchetti set, while in package-set it is already present...

**Comment by justinwoo** [comment]
You can use Behaviors if you want to use an FRP library: https://github.com/paf31/purescript-behaviors

And Event if you want a events library https://pursuit.purescript.org/packages/purescript-event/1.2.4/docs/FRP.Event

**Comment by f-f** [comment]
@voland62 I second Justin's suggestion, and add that we'd welcome if you could Pull Request the missing library to [spacchetti](https://github.com/spacchetti/spacchetti) 🙂

**Comment by voland62** [comment]
@justinwoo: Thx for suggestions. But I can't use purescript-event library(purescript-behavior's only instance of IsEvent class [except Semantic one]) for my needs due to luck of "true" switch operator, witch is impossible with "cold" events which ps-events implements...

  @f-f:  I can add sodium via ordinary spago addition without any problem, so I'm not sure we need PR for that...
