### ISSUE TITLE
Migrate Bower projects when doing `init`

### ISSUE THREAD

**Issue by antislava** [spacchetti/spago#159]
It would probably be nice to be able to have the dependency list as an optional input parameter to `spago init`, especially when working with existing packages based on `bower`. I suspect this is somehow related to #24 but I wasn't sure about the main focus there (most links there refer to no longer existing pages, e.g. `from-bower` scripts). Alternatively, one could optionally, define dependencies list in separate file `spago-dependencies.json` (which, being a simple list of strings, would also be a valid `dhall` file imported by `spago.dhall`). This file could be generated or overwritten by a simple script (probably, as a temporary solution before deciding whether to integrate the dependency import functionality deeper into the `spago` tool or not - most likely, it should remain a separate command/script keeping in mind the principle of separation of concerns), e.g.
```
jq '(.dependencies? | keys? // []) + (.devDependencies? | keys? // []) | map(ltrimstr("purescript-"))' ./bower.json > spago-dependencies.json
```

```
cat spago.dhall

{ name =
    "package-name"
, dependencies =
    ./spago-dependencies.json
, packages =
    ./packages.dhall
}
```

**Comment by f-f** [comment]
Hi @antislava! This is a good analysis, and I think it'd be worth adding your script to a FAQ section "Migrating from bower"

The next step after documenting this would be to automatically migrate a bower project when finding one. We do already migrate psc-package projects automatically in `spago init`, and I think it would be good to also support `bower.json` migration in the same way (that is, I don't think we should be able to provide options to init, as it should just detect the bowerfile)

I probably won't manage to do this myself as I'm concentrating on other things on the road to 1.0 (because your script does the job pretty well already), so I'll mark this as "help wanted" and I'm available to provide support, answer questions and give pointers if someone wants to implement this 🙂 (this is valid also for #24, which is about importing bower dependencies as `additions` in your local package set)
