### ISSUE TITLE
Parse error when `packages.dhall` doesn't follow the template format

### ISSUE THREAD

**Issue by jmackie** [spacchetti/spago#162]
The following `packages.dhall` file will throw a surprising parse error:

```
let overrides = {=}

let additions = {=}

let mkPackage =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.3-20190312/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

let upstream =
      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.3-20190312/src/packages.dhall sha256:379a4e0b19b1c1977d053d6cdd9403c579014f2cbdeab8b72700a1ae438b6897

in  upstream // overrides // additions
```

If this _must_ be an error, it probably shouldn't be described as a parse error. Cos it is valid Dhall and therefore should parse. Something more along the lines of _"packages.dhall should follow the standard format so that we can implement much of the functionality"_  would be more appropriate?

The relevant code is: https://github.com/spacchetti/spago/blob/master/app/Spago/PackageSet.hs#L117-L139

**Comment by f-f** [comment]
Thanks for the report @jmackie!

We currently use the `withPackageSetAST` function (the one with the problematic side-effect) in three places:
1. possibly upgrading the package set version when running `spago package-set-upgrade`
2. checking that the package set version is compatible with the `purs` version every time we might install something (i.e. for most of the commands)
3. checking that the package set import is frozen, i.e. it has hashes on it (same as above)

Now, for case `1.` the function has the context to decide if it's worth to abort the execution (because it cannot do anything if it cannot find the import), but in the other cases the execution can continue even if this operation is not possible.

So I think we should:
- not throw `die` [here](https://github.com/spacchetti/spago/blob/8cbdd54e7f7f9a9881bed050622e84be12254786/app/Spago/PackageSet.hs#L137), but instead just `echo`.
  Actually I'm not happy with the `with` idiom here, so probably a nicer refactoring would be to have `readRawPackageSet :: m (Either SomePackageSetError RawPackageSet)` and `writeRawPackageSet :: RawPackageSet -> m ()` instead, so the caller can decide what to do and when, and we can handle the errors properly with `Either` (this would fix also some other awkward bits around)
- For doing `1.` we have to specifically search for a remote import to the `package-sets` repo. Right now we search for it in a specific location, but I think it's _possible_ to do something like "search for this specific import across the AST" (though I have the feeling that to enable these specific queries we'd need to do [`makePrisms`](http://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-TH.html#v:makePrisms) on [Dhall's `Expr` type](https://github.com/dhall-lang/dhall-haskell/blob/bf067eeb69025e4ca918dbd64aad335657d56712/dhall/src/Dhall/Core.hs#L327))
- If the above is possible, then we should also do something like "freeze all imports in this AST" for `3.`
- For `2.` we need again to search specifically for the remote import of the `package-sets` repo (because it's the only one that has tags that match our expectations), but we should make a distiction between:
  1. the case in which we find this remote (assuming we can search through the AST), but the tag doesn't match: then we should error out if needed (but this happens [here](https://github.com/spacchetti/spago/blob/8cbdd54e7f7f9a9881bed050622e84be12254786/app/Spago/PackageSet.hs#L117-L139) already
  2. the case in which we have no idea what's going on (i.e. cannot find the import, or the import is local, etc). Then we should either have a lighter warning or no warning at all
