### ISSUE TITLE
Global spago repl

### ISSUE THREAD

**Issue by FintanH** [spacchetti/spago#168]
Something I often do with `stack` is just open a terminal and do `stack ghci` or `stack ghci --package text --package bifunctors` and play around with types and what not.

This doesn't seem possible with `spago` at the moment, would it be worth implementing this?

**Comment by f-f** [comment]
Yeah this is a cool idea!

As it happens with `stack`, `spago` needs a package set to refer to. So it's possible to do `stack ghci --package text --package bifunctors` because stack has the concept of "global project".

If you want to do this with spago now you would do (assuming you want to play with `bifunctors`):
```
$ mkdir temp-whatever && cd temp-whatever
$ spago init
$ spago install bifunctors
$ spago repl
```

I wouldn't like to have a "global project" as stack has (the usual problem is that it's stuck on an old lts version), so a global repl could just be implemented like the above sequence of commands (but transparently to the user):
- make a temporary directory somewhere like `/tmp` (or the equivalent on windows)
- run init
- install the needed packages
- open a repl

I won't get around to do this for a while, so I'll mark it as "help needed" and I'm available to provide guidance on the implementation 🙂 (which should be fairly simple)

**Comment by f-f** [comment]
While #133 is not _strictly necessay_ to have this, a global repl that has to download dependencies every time is not that nice, so it's better to wait for #188

**Comment by f-f** [comment]
Update: #188 went in, so this is not blocked anymore

**Comment by sohang3112** [comment]
> While #133 is not _strictly necessay_ to have this, a global repl that has to download dependencies every time is not that nice, so it's better to wait for #188

Definitely agree with this. I just installed PureScript, and it's already frustrating that every time I launch an REPL, I first have to wait for its whole library to compile!!

**Comment by f-f** [comment]
@sohang3112 the PR that fixes that has been merged and the REPL should be using cached dependencies, are you seeing a different behaviour?

**Comment by sohang3112** [comment]
> @sohang3112 the PR that fixes that has been merged and the REPL should be using cached dependencies, are you seeing a different behaviour?

@f-f Yes I'm seeing this behaviour with `spago repl` (in the "global" environment - i.e., without running `spago init` first). That is, `spago repl` emits a lot of *Compiling {lib}* messages where `{lib}` is a standard library. Running `spago repl` the second time is exactly the same as the first time - lots of *Compiling* messages.

### Environment Details
- Spago Version - 0.20.3 (latest)
- Purs Version - 0.14.5 (latest)
- OS: Ubuntu 20.04 (64 bit)

Please let me know if you require any other details also.

**Comment by f-f** [comment]
Right, this is because we don't want to assume that when you run a global repl twice in a row then we can share compilation results. They are considered two independent environments right now, so we have to recompile all dependencies.

There have been discussions about sharing compilation artefacts between builds, but the direction so far is so that the compiler should take care of this.

So if you want to reuse compilation results setting up a project (with `spago init`) is the easiest path right now
