### ISSUE TITLE
Question about separating executables / tests from libraries

### ISSUE THREAD

**Issue by blinky3713** [spacchetti/spago#178]
There's a lot of good documentation here, maybe this is in there but I didn't see it at first glance. One of the biggest pains for me with using `pulp` + `bower` versus something like `cabal` is that there's only two categories for dependencies -- `dependencies` and `devDependencies` -- which really sucks when you have multiple executables, a test suite, and a library in the same project.

My fallback is of course using a `Makefile` or an elaborate `package.json`, making sure I separate _anything_ not used by the library from whatever's in the `src` directory, and use a million pulp flags and args. I'm wondering what `spago` is able to do to help, or what's in the plan.

**Comment by f-f** [comment]
Hi @blinky3713! So far the direction has been to improve monorepo support in spago (e.g. see #158, #162, #163), in order to support better these usecases (the reasoning is that "monorepo support" covers this and other use cases)

So for example your situation could be handled by having multiple `spago.dhall` config files for the lib and the executables.  
E.g. let's say you have the following tree:
```
.
├── app
│   ├── spago.dhall
│   ├── src
│   │   └── Main.purs
│   └── test
│       └── Main.purs
├── lib
│   ├── spago.dhall
│   ├── src
│   │   └── Main.purs
│   └── test
│       └── Main.purs
└── packages.dhall
```

Then:
- the top level `packages.dhall` is standard and contains the link to the upstream and project-level overrides, etc
- `lib/spago.dhall` might look something like this:

```hs
{ name =
    "my-lib"
, dependencies =
    [ "effect"
    , "console"
    , "psci-support"
    , "prelude"
    ]
, packages =
    ../packages.dhall   -- Note: this refers to the top-level packages file
}
```

- `app/spago.dhall` might look something like this:

```hs
{ name =
    "my-app"
, dependencies =
    -- Note: the app does not include all the dependencies that the lib included
    [ "prelude"
    , "simple-json" -- Note: this dep was not used by the library, only the executable uses it
    , "my-lib"      -- Note: we add the library as dependency
    ]
, packages =
    -- We refer to the top-level packages file here too, so deps stay in sync
    -- and we also add the library as a local package
    (../packages.dhall) //
    { my-lib =
        { repo = "../my-lib"
        , version = ""
        , dependencies = (../my-lib/spago.dhall).dependencies
        }
    }
}
```

With this setup you're able to decouple dependencies in the library and in the executables.

This does not cover test dependencies, but I've yet to see a real-world case in which test dependencies add considerable time to a build

Also there are issues with this setup, e.g. if you use the `--watch` flag while running e.g. `spago build` on the app and you change something in the library, then the changes won't be picked up (as spago is watching only on app sources changes). This is tracked in #172 

Does this answer your question or is this not relevant at all?

**Comment by blinky3713** [comment]
awesome, that's totally relevant!

FWIW I'm not usually worried about build times when it comes to these things (I've learned to become pretty patient over the years), but for me it's often about dependency management. Like if the test suite uses `purescript-node-process` to grab some environment for the test suite, I don't want this to effect any versions of anything I want to use in `/app`. But it sounds like what you're saying is that I could just follow a similar pattern for `/test` as I would for `/app` to achieve this.

**Comment by f-f** [comment]
Great to know this works for you! 🎉 
Please report any other issues you might run into while trying this setup, as I suspect it still has some rough edges wrt project files management.

I'll keep this issue open as I think this is FAQ-worthy
