### ISSUE TITLE
Handle the case where the compiler version is newer than the package set compiler version

### ISSUE THREAD

**Issue by hdgarrood** [spacchetti/spago#225]
For example, trying to build a v0.12.5 package set with a v0.13.0 compiler:
```
spago: Oh noes! It looks like the PureScript version installed on your system is
outdated for the package-set you're using.

installed version:   0.13.0
package-set version: 0.12.5

Please upgrade your `purs` version.
```
Also, is it possible to tell spago that I know what I'm doing and I'd like to disable this check?

**Comment by f-f** [comment]
This is "handled" meaning that it has been thought about:
https://github.com/spacchetti/spago/blob/82c72fb7418e1a1b36aa00876d7aba5f2053739d/app/Spago/PackageSet.hs#L171-L178

..however the error message is wrong (it should say "too new" instead of "outdated").

Also there is no "nice" way to tell spago to just go on, so I think we should add a flag `--no-purs-check` that would skip this check entirely.

You can "hack" your way around this for now by adding a layer of indirection when importing the `packages.dhall` in `spago.dhall`, so:
- rename the `packages.dhall` to something else e.g. `packages1.dhall`
- make a `packages.dhall` containing the following: `./package1.dhall`

(this works because `spago` looks at the `packages.dhall` and searches for a GitHub url to determine the version of the package set. This should really be rehauled and we should have the package set version inside the package set data. See https://github.com/purescript/package-sets/issues/96 for more info)

**Comment by f-f** [comment]
In the end it looks like we can fix this without adding a new flag, through a combination of https://github.com/spacchetti/spago/pull/253 and https://github.com/purescript/package-sets/pull/343
