### ISSUE TITLE
Feasibility of using spago (or modified spago) for ReasonML projects?

### ISSUE THREAD

**Issue by andywhite37** [spacchetti/spago#226]
I've been working on some ReasonML projects, and I think the use of package sets and a tool like spago would solve a lot of headaches in dealing with some of the dependency issues that we currently face in the Reason/npm ecosystem.  I'm mainly interested in trying to wrangle the Reason-specific dependencies, and not the pure JavaScript dependencies, as that is a different problem.

The way the purescript package sets are setup seems generic enough to work for Reason projects (i.e. a package is just a pointer to git repo/ref and a list of dependencies).  I haven't looked in-depth at the spago code, but I was curious how feasible it might be to use or re-purpose spago to install libraries for use in Reason - e.g. dumping libs in node_modules in the way that the Bucklescript compiler expects.  I'm not proposing that spago be changed to do this - just curious what it might look like, or where to look in the code to see how package installation works.

**Comment by f-f** [comment]
Hi @andywhite37, this is a really interesting question!

I agree with you that Spago is generic enough that it would not be that hard to adapt to other ecosystems, and the idea of supporting ReasonML is quite intriguing per se.
I think it should be possible to support this in mainline here (that is, without needing to fork) and I would be in favor of doing so - for many reasons: because package sets are good and everyone deserves them, because it would be healthy for the codebase to isolate language-specific bits, because more usage means better tested code, etc

So if you wish to do this I'm available to help navigating the codebase, detailing assumptions, etc etc 🙂 

The "social" requirement for this to happen in mainline is that we'd get a maintainer using ReasonML, i.e. someone responsible for the ReasonML part and available to support users - because I don't use Reason nor plan to use it in the short-medium term, so if bug reports come in I won't be able to answer.   
A similar situation happened with Windows+PureScript where I wasn't able to answer to bug reports, but fortunately there it turned out well as many users stepped up to help with patches.   
However here I feel we'd need someone more involved with the codebase in order to feel ok about "we're supporting this", because I think it's a harder problem than cross-platform-compat (which is mostly solved by existing libraries, so one only needs to know the right incantations).  
So I'd suggest that before taking up the "spago+Reason" project you (or whoever will implement this) take on implementing some smaller issues (look for the "good first issue" ones) to familiarize yourself with the codebase

The "technical" requirements for this are about "what is PureScript dependent in spago and how we can use it for another language in practice". Off the top of my head:
- The [Purs module](https://github.com/spacchetti/spago/blob/master/app/Spago/Purs.hs) is "shimming" all the compiler-related operations. It's likely that the Reason compiler takes different options than the PureScript one, so I think the sanest route here is to make another CLI program (e.g. `spaml`?) that has a different interface than spago for compiler-related stuff. Then we wouldn't need a configuration switch, as Reason projects would just use `spaml` and the right environment will be set up for them (i.e. I guess we'd add an option to `GlobalOptions` at startup)
- The "default package set" is also a dependency, but at the moment much more spread out around the codebase. Spago assumes its location in many places (e.g. for upgrading the package set, for detecting the package set version, for getting the package index metadata, etc) so we'd have to make that swappable too
- Dependency downloads should be fine, because as you said it's just about fetching a git repo at some specified ref. Once you set up a package set you'll get for free global caching, dependency resolution, package sets version handling, etc
- There must be other stuff, but I guess we'll figure out as we go

Does this make any sense?

If you want to see what the packages-handling part looks like, check out the `Spago.Packages`, `Spago.PackageSet` and `Spago.FetchPackage` modules

**Comment by f-f** [comment]
Btw, what would be the usecase for this? That is, how's the package manager situation in Reason? 

E.g. [Dune](https://github.com/ocaml/dune) looks pretty cool, but I don't know if that's OCaml only, etc. (I have absolutely no idea about package management in Reason-land, so assume I know nothing)

**Comment by andywhite37** [comment]
Thank you for your reply!  The things you pointed out in the code make sense, and your other comments about getting familiarity with the spago code, and becoming a core point-of-contact for Reason things make sense too.  I'll take a look at the spago code and try to get more familiar with it, and try to figure out what the next step(s) might be.

I just saw your other comment come in, and I actually don't know much about `dune` either.  I started using Reason from the pure web frontend/bucklescript side, where packages are managed via `npm` and compiled with the bucklescript compiler, which knows about `npm` packages.  I haven't tried any native OCaml/dune/esy/etc. at this point.  I know the tools are starting to converge between native ocaml and some of the OCaml-to-JS tools, but I don't have a wide breadth of experience.  My main wish is to just have a way to get out of the npm dependency hell where libraries are allowed to install their own dependencies, and you frequently end up with duplicate/mis-matched version errors.

It's possible that dune or some other tool is solving this problem in a different way, but I'm intrigued by the idea of package sets, and spago seems to have implemented them in a really nice way, so I wanted to explore the idea.

**Comment by f-f** [comment]
@andywhite37 I was taking a look around the open issues, and I noticed your comment in https://github.com/reazen/relude/issues/91#issuecomment-519355876

Since I'd like to keep the issue tracker as "actionable" as possible, I'm going to close this issue for now. Let's reopen if/when there's bandwidth to work on this 🙂

**Comment by andywhite37** [comment]
@f-f - no problem, yes, let's close this for now.  I'll re-engage if I end up having some free time to look into it again.  Thanks for your help!

**Comment by f-f** [comment]
You're welcome 🙂
