### ISSUE TITLE
repl command fails on Windows

### ISSUE THREAD

**Issue by MuratOzsoyler** [spacchetti/spago#227]
`spago repl -- --port 3600` command fails on Windows.

This error is given:
`spago.exe: purs: callProcess: does not exist (No such file or directory)`

When I add the -v option to print the `purs` command executed output does not change.

purs command itself also results in the following error message, but apparently runs:
`purs repl: No input files; try running 'pulp psci' instead.
For help getting started, visit https://github.com/purescript/documentation/blob/master/guides/PSCi.md
Usage: For basic information, try the '--help' option.

I have installed the package as per `spago README.md`.

Any suggestions?

**Comment by f-f** [comment]
Hi @MuratOzsoyler, thanks for the report!

Some questions:
- Have you run `spago install` before `spago repl`?
- What version of `spago` are you on? (do `spago version` to know)

From the error it looks like `spago` cannot find `purs`, but you seem to be able to call `purs` directly so I'm a bit confused. Pinging some Windows users: @stkb @btrepp

**Comment by stkb** [comment]
Oh, yeah it'll be this old problem...

https://github.com/spacchetti/spago/blob/71c596af5e42d5c2691a57fe97143292d3308fcf/app/Spago/Purs.hs#L29-L35

For the repl command, `purs` is called with `callProcess`, except @MuratOzsoyler likely has PureScript installed with NPM, meaning there isn't a `purs` process, only `purs.cmd`.

In all the other commands, `purs` is called under a shell, so it works.

A workaround is [download the PureScript binary directly](https://github.com/purescript/purescript/releases/download/v0.13.0/win64.tar.gz); extract the `purs.exe` file from there and put it on your path, or install PureScript with [Chocolatey](https://chocolatey.org/) or [Scoop](https://scoop.sh/)

**Comment by f-f** [comment]
psc-package has [this piece of code](https://github.com/purescript/psc-package/blob/master/app/Main.hs#L217-L225) that makes it work I guess

**Comment by stkb** [comment]
@f-f I was already working on a quick fix that simply replaced the `callProcess` with [`callCommand`](http://hackage.haskell.org/package/unliftio-0.2.10/docs/UnliftIO-Process.html#v:callCommand), but that psc-package way is definitely another way to do it.

The `Purs.hs` module could do with some rewriting anyway as there's quite a bit of repetition there. Currently most of the code uses a `runInShell cmd` pattern rather than `runProcess path args`. Is there a reason to go with one over the other?

Another scenario we should make sure we support: If purescript is installed locally to the project under npm then we should run that version and not the global one. I think one of these PS tools had code for that, but I forget which one.

**Comment by MuratOzsoyler** [comment]
Thank you for prompt replies. `purs.exe` solved the problem.

I also admire the speed of commiting a quick fix by the way 👍

**Comment by f-f** [comment]
@MuratOzsoyler you're welcome 🙂 (and thanks @stkb!)

**Comment by f-f** [comment]
@stkb re `runInShell` vs `runProcess`: honestly I don't remember the rationale, when I coded that module I just wanted to get things to work. I'd be fine with a rewrite of the `Purs` module, it's a bit messy at the moment 🙂
