### ISSUE TITLE
Fails to install branches with / in the branch name

### ISSUE THREAD

**Issue by codedmart** [spacchetti/spago#257]
We commonly use branch names like `kimi/update/table`. Spago fails to install branches with `/` in the branch name. Example output error that I am seeing.
```
spago: Installation failed.

Error:

.spago/__download-lumi-components-kimi/update/table-c8f2fba29333e838: createDirectory: does not exist (No such file or directory)
```

**Comment by f-f** [comment]
This should be fixed anyways, but I'll note that branches are not really recommended with `spago`: the reason is that if you push more commits to the branch after you installed it once, spago won't pick up the new changes and you'll have to delete the `.spago` folder in order to make it pull the new stuff.

You could avoid all of this by just pointing at commits
