### ISSUE TITLE
Allow pass-through flags for `spago docs`

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#294]
`purs docs` accepts a `--format` flag that can be used to generate Markdown documentation and Vim/Emacs tags as well as HTML (the default). Currently `spago docs` doesn't accept any arguments, so you always get HTML. Could we allow e.g. `spago docs -- --format ctags` in the same way that `spago build` accepts pass-through arguments?

If we think it's a good idea, I'm sure I could PR this!

**Comment by justinwoo** [comment]
i've needed this sometimes as well, and using the same mechanism is probably easiest

**Comment by f-f** [comment]
@elliotdavies sounds good!

However, I'd prefer to not pass arbitrary arguments to `purs docs`, but have `--format` as a Spago flag. This is because we'll need to do other stuff than just calling `purs` when having html output (see #89)
If @justinwoo needs other flags other than `format`, we can add them as Spago flags too

**Comment by elliotdavies** [comment]
@f-f OK great - makes sense to me. I'll get on it!
