### ISSUE TITLE
Specify config path

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#329]
Since we can make more specific configs based off of spago.dhall, we should be able to specify specific configs.

Example:

MunProjekti420 has the following files:

```
src/Main.purs
src/Generated.purs
test/Main.purs
```

I would like to build and run only src/Main.purs, but non ni, Generated and Test.Main ovat rikki.

Jesusteippilla:

```dhall
# kekkonen420.dhall
./spago.dhall // { sources = [ "src/Main.purs" ] }
```

Kaunis. Nyt voimme rakentaa projektimme rauhassa.

```
spago run -c kekkonen420.dhall
```

**Comment by f-f** [comment]
@justinwoo if you don't want me to answer in Italian please stick to English so everyone can read this 😉

To answer your question: the "spago workflow" for this is to use the [monorepo support](https://github.com/spacchetti/spago#separate-devdependencies-or-test-dependencies), so you make your `kekkonen` folder and put a `spago.dhall` in there.

I wouldn't like to make the config name configurable, because it's useful to assume its location for a bunch of things.

**Comment by justinwoo** [comment]
The monorepo idea really doesn't work for making libraries, and is overall not really desirable. It seems like this is basically the equivalent of what people want with "development dependencies/tests" also, but without requiring any file juggling. Otherwise, users could come up with horrible Makefile hell to shuffle different spago.dhall files and/or move the output directory around, but that doesn't seem like it would serve anyone well.
