### ISSUE TITLE
Add `--deps-only` flag to `spago build`

### ISSUE THREAD

**Issue by justinwoo** [spacchetti/spago#330]
Many times you will change deps in your project, and want to then interactively fix your codebase.

**Comment by f-f** [comment]
@justinwoo could you detail an example?

**Comment by justinwoo** [comment]
```
$ psc-package build --help
Usage: psc-package build [-d|--only-dependencies] [`purs compile`-options]
                         [--jobs ARG]
  Install dependencies and compile the current package

Available options:
  -d,--only-dependencies   Compile only the package's dependencies
```

if you remove deps you don't want in your project, your project doesn't build anymore. however, you still want to actually develop interactively at the leaf modules of your codebase.

**Comment by f-f** [comment]
I'm not sure I understand how this can happen. Assuming you have dependencies `a`, `b`, `c` and your project builds using all of them:
- if you remove `a` then your project stops building. It doesn't make sense to rebuild only dependencies because the dependencies have already been built once
- if you add `d` then your project should rebuild just fine even if you include project code

**Comment by justinwoo** [comment]
This is also a problem when you upgrade packages, which is the equivalent of removing a package to add another.

**Comment by justinwoo** [comment]
Another crucial detail is that it's not like all non-project sources will be built guaranteed, especially if module headers are parsed first and the compiler determines that there are no valid build plans (for good reason)

**Comment by justinwoo** [comment]
Really, the only actual workaround for this missing feature is to `rm -rf src test && spago build && git checkout .`

**Comment by f-f** [comment]
We had a IRL chat with @justinwoo and it turns out the reason why you want to compile deps-only is for cases in which you:
- switch branches and there's a significant diff of deps
- update dependencies that introduce breakage

..and still want your `purs ide` to give you meaningful suggestions.

So you'd do `spago build --deps-only` and then start `purs ide`
