### ISSUE TITLE
Locate packages.dhall based on spago.dhall

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#349]
In `src/Spago/PackageSet.hs` the `ensureFrozen` function looks up the package set and logs a warning if it can't find it: https://github.com/spacchetti/spago/blob/2d349cc7c1ce02769688e136bdf9a3939c04ed35/src/Spago/PackageSet.hs#L302

At the moment the path for this is hard-coded to `packages.dhall` in the same directory: https://github.com/spacchetti/spago/blob/2d349cc7c1ce02769688e136bdf9a3939c04ed35/src/Spago/PackageSet.hs#L93

In a monorepo setup, where there is likely to be a single root `packages.dhall` but many distributed `spago.dhall` files, this means Spago commands almost always trigger this warning.

Given that the `spago.dhall` files must define a path to the `packages.dhall` anyway, would it make more sense to read and evaluate that path instead? This would give monorepo users the benefit of the check actually running, as well as reducing unnecessary warnings.

**Comment by f-f** [comment]
@elliotdavies yeah, we feel the need for this in our setup too.

I think this is not super hard to fix, but the implementation might get a bit involved. I think there are basically two ways here:
- try to follow the imports from the `spago.dhall` and see if we stumble on a file that has a remote import to the package set
- ..or since Dhall is doing this work already we could implement our version of [`input`](http://hackage.haskell.org/package/dhall-1.25.0/docs/Dhall.html#v:input) that instead of throwing away the `Status` (that contains the resolved imports), it looks into it and gives us the path of the "real" `packages.dhall` (disclaimer: I'm not sure how feasible this is, but it might work)

**Comment by elliotdavies** [comment]
@f-f My preference is to follow the imports ourselves, because `input` seems like quite a core thing to reimplement.

If we are OK to enforce that the file containing the package-set remote import is always called `packages.dhall` then I think this fix is actually fairly simple, because we'll know which file in the tree needs its imports checked. (We'll have to guard against finding multiple files with that name.) I also think such a restriction would avoid problems in #393.

However, situations have come up before where people name their files differently, such as in the example in #163. If we therefore choose not to enforce `packages.dhall` as a filename then I think we'll have to choose between:
- Gathering up any and all remote imports that we find, and running the frozen check on all of them (this is actually what we do now, except on a single file)
- Attempting to determine which imports to check, but I think this would require some possibly fragile string pattern matching

**Comment by f-f** [comment]
@elliotdavies I mentioned "following the imports" but I mean it as a last possibility if nothing else works. This is because Dhall is already doing it, so we'd have to duplicate code and duplicate work.
On the other hand the code for `input` (which is not a "core" thing but just there for convenience of not having to `parse`/`import`/`typecheck`/etc by yourself) is already duplicated in slight variations all over Dhall's codebase itself, and everyone that implements any non-default interpreter ends up having their own implementation of it.
I think this is our case too so we should try going with this first.

[Here's one reimplementation of it](https://github.com/dhall-lang/dhall-haskell/blob/0ebf705a75bf0e1b2e712ca4d826d749abb5c940/dhall/src/Dhall/Main.hs#L367-L386), and in line 370 there is a call to `evalStateT`. The `StateT` in question is the [`Status` from here](https://github.com/dhall-lang/dhall-haskell/blob/0ebf705a75bf0e1b2e712ca4d826d749abb5c940/dhall/src/Dhall/Import/Types.hs#L56-L75), where we have the `_stack` containing a list of all the imports found so far.

I feel (but I'm not sure, need an implementation to actually confirm this) that if we recover that `_stack` from the evaluation then we can go through all the `Remote` imports and `freeze` them.
In order to recover it we should change that
```hs
evalStateT :: Monad m => StateT s m a -> s -> m a 
```
to
```hs
runStateT :: Monad m => StateT s m a -> s -> m (a, s)
```
..so that we can recover the final `Status` in addition to the result of the evaluation. 

To answer your other concern about enforcing the `packages.dhall` name: I think it's fine to assume that we'll have a `packages.dhall` when we try to read it directly (e.g. for the `upgrade-set` command), but we should not fix this name if it gets imported somewhere - so e.g. a `spago.dhall` importing a `packages-something.dhall` would still be accepted

**Comment by elliotdavies** [comment]
@f-f Huh... fair enough! I'm not that familiar with the Dhall codebase and `input` seemed more important than it was 😁 If people often reimplement variants of it then yes, I agree we should try that. I'll give it a go based on what you've suggested here.
