### ISSUE TITLE
Check whether additions are already in the package-set

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#372]
This could be part of `spago upgrade-set`, or definitely looks related to the future `spago upstream` as outlined in #72, but -- it would be nice if there was an easy way to check whether an addition in `packages.dhall` is already in the package-set. At the moment it's quite easy to leave them in there unnecessarily, or even accidentally restrict yourself to an old package version (e.g. if you had added something locally at `v1.0.0` but later `v1.0.1` gets added to the upstream).

**Comment by f-f** [comment]
@elliotdavies this is handled by Dhall, which has different operators for record merging.

Currently we're using the "non-recursive right-biased record merge" operator `//` to merge `additions` and `overrides` and so on.
This means that the record on the right always overrides the one on the left, example:
```
$ dhall <<< "{ foo = 1 } // { foo = 2 }"
{ foo = 2 }
```

However if you want to prevent overriding already defined record fields you could use the "recursive record merge" operator `/\`, that will error out if you try to redefine packages. Example:
```
$ dhall <<< "{ foo = 1 } /\ { foo = 2 }"

Use "dhall --explain" for detailed errors

Error: Field collision

1│ { foo = 1 } /\ { foo = 2 }

(stdin):1:1
```

So in your case you could do `packages /\ overrides /\ additions` instead of `packages // overrides // additions` in your `packages.dhall`

**Comment by elliotdavies** [comment]
@f-f Oh that's neat! I didn't know about that. It's a shame it doesn't report _which_ field collided (unless you turn on `--explain`, in which case it's very verbose) but yeah, no need to do anything in Spago I don't think. I shall close this :smile:

**Comment by f-f** [comment]
You're welcome 🙂
