### ISSUE TITLE
Install for `halogen-formless` fails

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#394]
Reproduction:
```bash
$ spago init
$ spago install halogen-formless
```

This gives the error:
```
spago: Installation failed.

Error:

Invalid file name in tar archive: "../bower_components/purescript-halogen-storybook/examples/src/Storybook.css"
```

@thomashoneyman any ideas?

**Comment by wryk** [comment]
link https://github.com/thomashoneyman/purescript-halogen-realworld/issues/43

**Comment by f-f** [comment]
Oh I tried searching only in the `halogen-formless` repo so I missed that issue. Thanks a lot @wryk!

**Comment by thomashoneyman** [comment]
@f-f Formless has a symlink in its `dist` directory, like this:

```
~/purescript-halogen-formless/dist $ ls -l
index.html
storybook.css -> ../bower_components/purescript-halogen-storybook/examples/src/Storybook.css
```

I can't remember why 😬 but I must have had some reason, because the CI build replaces the symlink with the actual file as part of building the documentation site:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/d7151f89d870b0e5647ac3ce76ec13d184e047b5/.circleci/config.yml#L51

I can remove that symlink now. I have some followup questions, though (you may not know the answers, but I'd like to figure them out!):

- Why did the package pass the `psc-package` verification step in the `package-sets` repository and locally and then fail with `spago install`?
- Previous versions of Real World and other projects manually included Formless as an addition to the package set. In fact, I believe my addition to `package-sets` was a copy/paste from the addition I was using in Real World. Why did the manual addition work, but the package set installation fail?

**Comment by thomashoneyman** [comment]
This is fixed by https://github.com/thomashoneyman/purescript-halogen-formless/pull/55. I know it's bad practice to adjust an existing tag, but given the trivial nature of the change (removing a symlink no one in practice would see using the library) and the consequence of breaking installations I thought it was the better option.

**Comment by f-f** [comment]
@thomashoneyman thanks a lot, this works now so I'll close the issue! 🙂 

> Why did the package pass the `psc-package` verification step in the `package-sets` repository and locally and then fail with `spago install`?

This is a great question, and I'll start by explaining why this failed locally: Spago will try to download tar archives from GitHub if possible (i.e. if the package you're installing is from GitHub and in package-sets) and `git clone` the repo (which is much slower) otherwise.
Full logic is here:

https://github.com/spacchetti/spago/blob/e988bbab99dd3c471c40a373b7d2e39bc5cc0e21/src/Spago/GlobalCache.hs#L38-L43

So the install failed here because the GitHub tar archive doesn't like links, but it succeeded when the package was not in `package-sets` because in that case Spago clones it so everything is fine.

We did not realize this in `package-sets` CI because that one uses `psc-package` only, and `psc-package` always uses `git fetch` and no tarballs.
Since we found out about https://github.com/purescript/package-sets/issues/451 too, we'll likely just add a verification with spago there
