### ISSUE TITLE
Revert #425

### ISSUE THREAD

**Issue by jjl** [spacchetti/spago#442]
Hi Fabrizio,

At [gargantext](https://gargantext.org/), we have been using spago to generate package sets for consumption with psc-package for several months now. In fact, at the time, we tried to use spago for everything but it was really very buggy and basic things did not work. Fortunately, package set generation has always been very reliable and we could use psc-package for the rest.

It's now only a few months later and we're faced with having to rewrite our build *again*. I do not know if spago will be reliable this time, but the fact that you've just shafted our build that we only rejigged a few months ago is not filling me with a great deal of confidence.

Please revert this change.

**Comment by f-f** [comment]
Hi @jjl, thanks for reporting your experience!

I'm sorry to hear about the bugginess. Did you try reporting issues (you or any of your colleagues) at the time? If yes, were they fixed?

Then I'd like to point out that there's no pressure whatsoever to rewrite your build and you can continue keeping it like this for years: `spago@0.10.0` is and will be on NPM and GitHub releases possibly forever, so you can just pin to that version.
This works because if your only usage is limited to the `psc-package`-compatibility commands, then you don't have to actually update ever, since the code for them has not changed since the first Spago release

..but it has only been refactored. And "maintenance" is in fact the main reason for dropping this code in #425: refactoring it together with the rest of the codebase does not make sense given that the logic never changes and you can stick with an arbitrary Spago version and get the same functionality.

So I would say there's no reason to worry about this, and that you should be worried only if `package-sets` would drop the `packages.json` file, which we're not planning to do anytime soon.

Does this make sense to you?

**Comment by jjl** [comment]
Hi Fabrizio,

I didn't report any bugs at the time. It seemed like it was just generally a quite buggy piece of software and the bit I needed to work seemed to be okay, so I just ran with that. I'm part time, alas, so I don't have the luxury of much time to spend on these things.

I understand what you're saying about package-sets, and indeed about refactoring, but it still sits quite uneasily with me. I have considered forking spago and turning it into just a cli for spacchetti. Perhaps other people might be interested in such a tool. From what you've said, it does seem rather like something that might be worth extracting.

**Comment by f-f** [comment]
@jjl 

> I didn't report any bugs at the time. It seemed like it was just generally a quite buggy piece of software and the bit I needed to work seemed to be okay, so I just ran with that

I don't know, in my experience this thing has always been fairly stable even in the early days and us maintainers have always strived to be responsive on "showstopper" bugs.
For this to work reporting needs to happen though, so I'd invite you to open issues if you ever stumble on problems again

> I have considered forking spago and turning it into just a cli for spacchetti

Indeed you could fork this and keep the codebase frozen to the commit before #425, but how's that different from just using `0.10.0` forever? (or `0.9.0`, or `0.8.0`, etc, since the only functionality that you're using hasn't changed ever)

> From what you've said, it does seem rather like something that might be worth extracting

What I'm trying to say is actually the opposite: this piece of code is not worth extracting and it's not even worth keeping around.
This is because since the functionality you need has not changed across releases and is not going to change ever (again, unless `package-sets` changes), so you can just use the latest release version of Spago or whatever other previous version

If you really want to extract it and put it somewhere, then the `psc-package` codebase would actually be the right place to integrate this into

**Comment by jjl** [comment]
I think you just told me my experience was wrong.

Giving up now.

**Comment by f-f** [comment]
> I think you just told me my experience was wrong

Not "wrong", but incomplete: the point I'm trying to make here is that anyone that walked in with a bug usually walked out pretty quickly with a fix

Anyways I tried to suggest some solutions above and I'd love to hear why you think they wouldn't work in your case. Could you detail more on this?

**Comment by jjl** [comment]
I didn't file a bug report because:
- I had several whole minutes of spago experience under my belt at the time
- The errors made absolutely no sense to me
- The entire feeling I was getting from trying to use it at the time was that it was junk and I was just lucky I managed to get through package set generation without something going wrong.

This may not be what you want to hear, but I swear it's an accurate reflection of my experience at the time. In general I try to avoid filing bugs when I wouldn't be able to put any useful information in them.

As for what we are going to do... We will stick on spago 0.10 and hope like hell there are no bugs in that code and that the package-set format doesn't change. And if it does, I will ensure that it's not my turn to fix it.
