### ISSUE TITLE
Concurrent spago usage is very slow

### ISSUE THREAD

**Issue by jmackie** [spacchetti/spago#451]
Reproduce with:

```bash
#!/usr/bin/env bash

cd $1
for i in {1..50}; do
  spago list-packages --filter direct --json &
done

wait
echo "Finished!"
```

Changing `n` in `{1..n}` significantly affects the execution time and I can't see any obvious reason why this would be the case.

**Comment by f-f** [comment]
According to my tests on our project at work I get:
- `~1.8s` with 5 concurrent calls
- `~25s` with 50 concurrent calls, which is roughly 10 times more

The reason why this makes sense is that this is a CPU-bound task, since we're calculating the transitive dependencies of the project independently at each invocation (note that this got significantly faster in the latest release thanks to #412, so maybe try that one if you're not on latest already)

What's your usecase for running many instances in parallel?

**Comment by jmackie** [comment]
Fair enough. My use case is/was a dodgy script that tried to graph the packages in our work monorepo. I've got a better solution now but I thought it was an observation worth raising. 

Cheers for the quick response though pal, keep up the good work :pray:

**Comment by f-f** [comment]
@jmackie thanks for detailing! Talking IRL with @justinwoo he figured this might be because of the Haskell Runtime (RTS) starving for resources. So we could try [passing some options to it](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-opts-cmdline) to reduce the amount of threads - e.g. try `spago +RTS --help` to see how you can tweak the runtime parameters

I'm going to close this issue since your initial problem seems to be solved, but let's reopen if we figure we want to do something about this!
