### ISSUE TITLE
Output more information about installation error

### ISSUE THREAD

**Issue by vyorkin** [spacchetti/spago#54]
For now, it just outputs:
```
spago: Installation failed.
```
I think it might be useful to output more contextual info about the installation error.

**Comment by f-f** [comment]
@vyorkin could you add more details about what you were trying to do? Also does rerunning the command fix it?

**Comment by f-f** [comment]
Cool, thanks 👍

Then I guess a good fix for this would be to print out the `git` commands output in case of error.

P.S.: are you basing multiple repos on your package set? Because if you have only one you can avoid maintaining your package set by depending on the upstream `spacchetti` and adding your overrides to the local `packages.dhall`

**Comment by vyorkin** [comment]
got it, thank you!
yeah, there are quite a few additional packages that I use pretty often https://github.com/vyorkin-forks/spacchetti/commit/4f886cf620b03dfb6a4942f0bf3c43f5b5551b97, so I've just decided to maintain a custom package set (I'm still not sure about this decision though)
